import type { Language, LatexBundle, ResumeDraft } from "./types";

/** Escape plain text so it is safe inside LaTeX arguments and `\item` bodies. */
export function escapeLatex(text: string): string {
  return text.replace(/[\\#$%&_{}~^]/g, (ch) => {
    switch (ch) {
      case "\\":
        return "\\textbackslash{}";
      case "{":
        return "\\{";
      case "}":
        return "\\}";
      case "#":
        return "\\#";
      case "$":
        return "\\$";
      case "%":
        return "\\%";
      case "&":
        return "\\&";
      case "_":
        return "\\_";
      case "~":
        return "\\textasciitilde{}";
      case "^":
        return "\\textasciicircum{}";
      default:
        return ch;
    }
  });
}

function heading(draft: ResumeDraft) {
  return {
    title: escapeLatex(draft.projectTitle),
    role: escapeLatex(draft.role),
    period: escapeLatex(draft.period),
    org: escapeLatex(draft.organization),
  };
}

function itemLines(draft: ResumeDraft): string {
  return draft.bullets
    .map((b) => `  \\item ${escapeLatex(b.text)}`)
    .join("\n");
}

function stackInline(draft: ResumeDraft): string {
  return draft.stack.map((s) => escapeLatex(s)).join(" / ");
}

function comment(lang: Language, extra: string[]) {
  const lines =
    lang === "en"
      ? [
          "% Generated by Xiangshu — paste into your resume class file.",
          "% Compile with XeLaTeX (or LuaLaTeX) if the bullets contain CJK.",
          ...extra,
        ]
      : [
          "% 由「项述」生成，可直接粘贴进你的简历类文件。",
          "% 含中文时请使用 XeLaTeX / LuaLaTeX。",
          ...extra,
        ];
  return lines.join("\n");
}

export function renderBillryan(draft: ResumeDraft, lang: Language): string {
  const h = heading(draft);
  return `${comment(lang, [
    "% 适配 Billryan/resume（\\datedsubsection + \\role + itemize）",
  ])}

\\datedsubsection{\\textbf{${h.title}}}{${h.period}}
\\role{${h.role}}{${h.org}}
\\begin{itemize}
${itemLines(draft)}
\\end{itemize}
`;
}

export function renderAwesomeCv(draft: ResumeDraft, lang: Language): string {
  const h = heading(draft);
  return `${comment(lang, ["% 适配 Awesome-CV（\\cventry）"])}

\\cventry
  {${h.period}}
  {${h.role}}
  {${h.title}}
  {${h.org}}
  {${stackInline(draft)}}
  {
    \\begin{cvitems}
${draft.bullets
  .map((b) => `      \\item {${escapeLatex(b.text)}}`)
  .join("\n")}
    \\end{cvitems}
  }
`;
}

export function renderModerncv(draft: ResumeDraft, lang: Language): string {
  const h = heading(draft);
  return `${comment(lang, ["% 适配 moderncv（\\cventry）"])}

\\cventry{${h.period}}{${h.role}}{${h.title}}{${h.org}}{}{%
\\begin{itemize}
${itemLines(draft)}
\\end{itemize}}
`;
}

export function renderItemize(draft: ResumeDraft, lang: Language): string {
  const h = heading(draft);
  return `${comment(lang, ["% 通用 itemize 片段，可放进任意 section"])}

\\subsection*{${h.title} \\hfill {\\small ${h.period}}}
{\\itshape ${h.role} · ${h.org}}\\\\
{\\small ${stackInline(draft)}}
\\begin{itemize}
${itemLines(draft)}
\\end{itemize}
`;
}

export function renderStandalone(draft: ResumeDraft, lang: Language): string {
  const inner = renderItemize(draft, lang);
  const title = escapeLatex(draft.projectTitle);
  return `\\documentclass[11pt,a4paper]{article}
\\usepackage[margin=22mm]{geometry}
\\usepackage{fontspec}
\\usepackage{xeCJK}
\\usepackage{microtype}
\\usepackage{enumitem}
\\setmainfont{TeX Gyre Pagella}
\\setCJKmainfont{Noto Serif CJK SC}
\\setlist[itemize]{leftmargin=1.4em, itemsep=0.35em, parsep=0pt, topsep=0.4em}
\\pagestyle{empty}
\\begin{document}

\\begin{center}
  {\\LARGE\\bfseries ${lang === "en" ? "Project Experience" : "项目经历"}}\\\\[0.4em]
  {\\large ${title}}
\\end{center}
\\vspace{0.6em}

${inner}

\\end{document}
`;
}

export function renderLatexBundle(
  draft: ResumeDraft,
  lang: Language,
): LatexBundle {
  return {
    billryan: renderBillryan(draft, lang).trim() + "\n",
    awesomeCv: renderAwesomeCv(draft, lang).trim() + "\n",
    moderncv: renderModerncv(draft, lang).trim() + "\n",
    itemize: renderItemize(draft, lang).trim() + "\n",
    standalone: renderStandalone(draft, lang).trim() + "\n",
  };
}

export function renderMarkdown(draft: ResumeDraft): string {
  const stack = draft.stack.map((s) => `\`${s}\``).join(" · ");
  const bullets = draft.bullets.map((b) => `- ${b.text}`).join("\n");
  return `### ${draft.projectTitle} · ${draft.role}
**${draft.period}** · ${draft.organization}${stack ? ` · ${stack}` : ""}

${draft.oneLiner}

${bullets}
`;
}
